version: '3.1'

services:
  wordpress:
    image: wordpress:4.9.8-php7.1-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - .:/var/www/html/wp-content

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - .data:/var/lib/mysql